### ISSUE TITLE
[목록] 카드의 설명 부분 텍스트가 두줄일 경우 짤리는 현상

### ISSUE THREAD

**Issue by seogi1004** [juijs/store.jui.io#10]
조금 높이를 키워야할듯!

**Comment by easylogic** [comment]
짤리는게 아니라 일부러 두줄에 맞춤 더 늘리면 디자인이 좀 이상함.

**Comment by easylogic** [comment]
일단 라이브러리 써서 모든 박스 동일하게 맞춤. 

이건 나중에 디자인이 너무 이상하면 높이를 늘리는건 상관 없음. 

일단 닫겠음.
