### ISSUE TITLE
[문서] 스토어 관련 문서 작성하기

### ISSUE THREAD

**Issue by seogi1004** [juijs/store.jui.io#15]
1. 스토어 소개
2. 스타일 테마 만들기
3. 차트 테마 만들기
4. 브러쉬 추가하기
5. 브러쉬 개발하기

**Comment by seogi1004** [comment]
[기본 요소 설명]
- brush 구조 및 빌더 동작 구조 설명
- drawBefore, draw, drawAfter 메소드
- setup 스태틱 메소드
- this 프로퍼티
- this.chart 프로퍼티
- this.chart.svg 프로퍼티
- this.axis 프로퍼티
- this.brush 프로퍼티

[chart 인스턴스 요소 설명]
- get 메소드
- axis 메소드
- area 메소드
- padding 메소드
- text 메소드
- texts 메소드
- theme 메소드
- render 메소드

[chart.svg 인스턴스 요소 설명]
- svg 태그 생성 메소드 룰
- size 메소드
- getTextSize 메소드

[svg element 관련 클래스 설명]
- Element 클래스
- TransElement 클래스
- PathElement 클래스
- PolyElement 클래스

[svg element 클래스 요소 설명]
- each 메소드
- get 메소드
- append 메소드
- prepend 메소드
- attr 메소드
- css 메소드
- html 메소드
- text 메소드
- on 메소드
- size 메소드

[axis 인스턴스 요소 설명]
- x 메소드
- y 메소드
- c 메소드
- map 메소드

[this(brush core) 요소 설명]
- eachData
- listData
- getData
- getValue
- getXY
- getStackXY
- addEvent
- color
- offset

**Comment by easylogic** [comment]
스토어 소개는 했음. 나머지는 api 는 어떤식으로 정리할지. 아님 api 사이트 그대로 쓸지 결정하삼 ~

**Comment by easylogic** [comment]
API 는 api 사이트 쓰는걸로
