### ISSUE TITLE
차트 맵 추가하는 기능 만들어주세요.

### ISSUE THREAD

**Issue by seogi1004** [juijs/store.jui.io#20]
이거까지 추가합시다!!!
아무래도 이것도 차트 테마나 스타일 테마처럼 많이 추가될 것 같음....
일단 컨텐츠가 엄청 많음...

amchart에 있는 맵들만 가져와도 도움이 많이 될듯...
어차피 부분 무료라서 스토어에 해당 라이센스 걸고 공개하면 좋을것 같음;;

물론 기준좌표는 내가 노가다로 찍어두고;;

**Comment by easylogic** [comment]
map 타입 추가 했으니 

임의로 추가 하면 됨.
