### ISSUE TITLE
모듈 작성하기, 기타 기능 기획

### ISSUE THREAD

**Issue by seogi1004** [juijs/store.jui.io#24]
1. 외부 리소스 링크
2. 스태틱 파일 업로드

**Comment by easylogic** [comment]
외부 리소스를 JSFiddle 처럼 공개된 cdn 의 경우 

링크만 바로 지원할 것인가?

**Comment by easylogic** [comment]
외부 모듈. 내부 모듈  

로드하기 
import 하기 (이건 스크립트 태그로 직접 넣는)

**Comment by easylogic** [comment]
화면 전체 Layout 을 좀 바꿔야할지도 모르겠음. 

information 을 계속 뛰워놓는건 좀 비효율 젃인것 같은데. .

layout 구조를 맞추는게 있으면 좋겠음. 

각 영역에 맞는 형태로 

예를 들어 

모듈 우선이면 

모듈이 제일 크고, 샘플 이랑 Result 가 작고 

Result 가 우선이면 Result 가 가장 크고 나머지는 하나의 영역으로 들어간다던가. 

암튼 무조건 4분할이 되버리니 공간이 조금 비효율적임.

**Comment by easylogic** [comment]
샘플은 무조건 하나의 html 만 만들기로.

**Comment by easylogic** [comment]
외부 리소스 넣는건 샘플의 기능으로 가야할 듯

**Comment by easylogic** [comment]
외부 소스 넣는건 module 에 구현 했음. store 한번 보삼. 

그리고 이걸로 인해서 문제가 좀 있는데 말이지. 

외부소스를 bootstrap 을 올리고 bootstrap 클래스를 써버리면 

jui css 랑 겹치는게 있으면  jui css 도 같이 적용되버리는 문제가 있음. 

기본적으로 jui.css 를 로드 하게 되어 있는데 

기본을 빼야할지 고민이 좀 됨. 

어떤식으로 해야할지.

**Comment by easylogic** [comment]
- [x] 외부 리소스 링크
- [x] 스태틱 파일 업로드

모두 적용
