### ISSUE TITLE
[공통] Style, Brush, Theme 라벨 이름 바꾸기

### ISSUE THREAD

**Issue by seogi1004** [juijs/store.jui.io#3]
Style Theme
Chart Theme
Cart Brush

명확하게 풀어야 할듯...

**Comment by easylogic** [comment]
라벨 너무 김. 한단어로 한것도 너무 길어서 그런디

**Comment by seogi1004** [comment]
근데 스타일이랑 차트 둘다 테마인데...
=ㅁ=; 고민을 좀 해봐야함

**Comment by easylogic** [comment]
Brush
Theme
Style

이렇게 함.. 

고민을 좀 해야겠군.

**Comment by easylogic** [comment]
Module, Chart Them, UI Theme, Map 

이렇게 정의됨.
