### ISSUE TITLE
presentation 모드 만들기

### ISSUE THREAD

**Issue by easylogic** [juijs/store.jui.io#40]
- settings 
  - 전체 테마 theme 
- section 
  - background : image or #dddd (color) 
  - background-video 
  - transition
  - background-transition 
- script

**Comment by egaoneko** [comment]
- section
  - data-markdown
  - data-separator
  - data-separator-vertical
  - data-separator-notes
  - data-charset
  - data-background-image
  - data-background-size
  - data-background-position
  - data-background-repeat
  - data-background-video
  - data-background-video-loop
  - data-background-video-muted
  - data-background-iframe
  - data-transition-speed
  - data-transition
- settings
  - 전체 테마 `<link rel="stylesheet" href="css/theme/black.css" id="theme">`
  - 초기화 `Reveal.initialize({});`
    - controls
    - progress
    - slideNumber
    - history
    - keyboard
    - overview
    - center
    - touch
    - loop
    - rtl
    - shuffle
    - fragments
    - embedded
    - help
    - showNotes
    - autoSlide
    - autoSlideStoppable
    - autoSlideMethod
    - mouseWheel
    - hideAddressBar
    - previewLinks
    - transition
    - transitionSpeed
    - backgroundTransition
    - viewDistance
    - parallaxBackgroundImage
    - parallaxBackgroundSize
    - parallaxBackgroundHorizontal
    - parallaxBackgroundVertical
    - width
    - height
    - margin
    - minScale
    - maxScale
    - dependencies

**Comment by easylogic** [comment]
객체 값을 바꿀 때는 그냥 지우고 다시 그리는게 속편할때가 많다.

**Comment by easylogic** [comment]
save, embeded, static  3 총 3가지로 저장할 수 있으면 된다.

**Comment by easylogic** [comment]
저장되고 수정되고 

static 파일이랑 embed 형식으로 볼 수 있고 

broadcast 개념을 만들어서 서로 연결해서 동기화 할 수 있다.  

리모콘 처럼 쓰는거지. 

거기다 관리자 모드 둬서 좀 더 편하게 제어할 수 있도록 해야겠다.

**Comment by easylogic** [comment]
note 를 볼 수 있는 기능도 넣어야한다.

**Comment by easylogic** [comment]
기본 기능 추가 완료. 

나머지는 이슈를 새로 생성해서 진행.
