### ISSUE TITLE
[편집/스타일] 샘플 선택 후에 테이블 필터링 문제

### ISSUE THREAD

**Issue by seogi1004** [juijs/store.jui.io#8]
필어터링하고 스타일 깨지는 현상 발생함...
table.resize(); 메소드 호출해줘야 함...

**Comment by easylogic** [comment]
이건 할까 말까 고민중. 그냥 그 위치로 가는 것도 괜찮은 듯. 필터링 안학ㅎ

**Comment by easylogic** [comment]
필터링 안하고 스크롤도 안하는 방식으로 감.
