### ISSUE TITLE
[편집/테마] 샘플 셀렉트 박스 위치 변경하기

### ISSUE THREAD

**Issue by seogi1004** [juijs/store.jui.io#9]
스타일은 Result에 있는데 테마에는 다른데 있음...
맞추는게 좋지 않겠음?

**Comment by easylogic** [comment]
Theme, Style 은 코드를 입력하지 않기 때문에 Sample 리스트를 Result 로 보냈음. 

Brush 의 경우는 샘플 코드를 직접 입력하기 때문에 그대로 둠.
